'use client'

import dynamic from 'next/dynamic'
import { useEffect, useRef, useState } from 'react'
const InspectionMap = dynamic(() => import('../components/InspectionMap'), { ssr: false })
type Detection = { label:string; confidence:number; bbox:[number,number,number,number]; trackId:number|null }
type EventRecord = { event_id:string; track_id:number; timestamp:string; latitude:number|null; longitude:number|null; confidence:number; bbox:number[]; severity:'high'|'medium'|'low'; evidence:string }
type RoutePoint = { latitude:number; longitude:number; timestamp:string }
type RouteData = { points:RoutePoint[]; distanceMeters:number; distanceKm:number; pointCount:number }
type Summary = { total:number; high:number; medium:number; low:number; routePoints?:number; routeDistanceMeters?:number }
type Analytics = { potholesPerKm:number|null; averageConfidence:number; confidencePercent:number; conditionScore:number|null; conditionLabel:string; mappedPotholes:number; unmappedPotholes:number; evidenceCaptured:number; hotspots:{eventId:string;latitude:number|null;longitude:number|null;confidence:number;band:string}[] }
const API_URL=process.env.NEXT_PUBLIC_VISION_API_URL||'http://localhost:8000'
const emptySummary:Summary={total:0,high:0,medium:0,low:0,routePoints:0,routeDistanceMeters:0}; const emptyRoute:RouteData={points:[],distanceMeters:0,distanceKm:0,pointCount:0}; const emptyAnalytics:Analytics={potholesPerKm:null,averageConfidence:0,confidencePercent:0,conditionScore:null,conditionLabel:'No data',mappedPotholes:0,unmappedPotholes:0,evidenceCaptured:0,hotspots:[]}
export default function Home(){
 const videoRef=useRef<HTMLVideoElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),streamRef=useRef<MediaStream|null>(null),timerRef=useRef<ReturnType<typeof setInterval>|null>(null),busyRef=useRef(false),gpsRef=useRef<[number,number]|null>(null)
 const [cameraOn,setCameraOn]=useState(false); const [inspecting,setInspecting]=useState(false); const [gps,setGps]=useState<'waiting'|'ready'|'unavailable'>('waiting'); const [gpsPoint,setGpsPoint]=useState<[number,number]|null>(null); const [coordinates,setCoordinates]=useState('Waiting for permission'); const [frames,setFrames]=useState(0); const [inferenceMs,setInferenceMs]=useState<number|null>(null); const [detections,setDetections]=useState<Detection[]>([]); const [events,setEvents]=useState<EventRecord[]>([]); const [summary,setSummary]=useState<Summary>(emptySummary); const [route,setRoute]=useState<RouteData>(emptyRoute); const [analytics,setAnalytics]=useState<Analytics>(emptyAnalytics); const [apiStatus,setApiStatus]=useState<'offline'|'online'>('offline'); const [selectedEvent,setSelectedEvent]=useState<EventRecord|null>(null); const [reportBusy,setReportBusy]=useState(false); const [completeBusy,setCompleteBusy]=useState(false)
 useEffect(()=>{gpsRef.current=gpsPoint},[gpsPoint]); useEffect(()=>{if(!navigator.geolocation)return setGps('unavailable');const id=navigator.geolocation.watchPosition(p=>{setGps('ready');setGpsPoint([p.coords.latitude,p.coords.longitude]);setCoordinates(`${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)}`)},()=>{setGps('unavailable');setCoordinates('Location unavailable')},{enableHighAccuracy:true,maximumAge:2000,timeout:10000});return()=>navigator.geolocation.clearWatch(id)},[])
 async function startCamera(){try{const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});streamRef.current=stream;if(videoRef.current){videoRef.current.srcObject=stream;await videoRef.current.play()}setCameraOn(true);return true}catch{setCameraOn(false);alert('Camera permission was not granted or no camera is available.');return false}}
 async function startInspection(){const ready=cameraOn||await startCamera();if(!ready)return;try{const r=await fetch(`${API_URL}/history/start`,{method:'POST'});if(!r.ok)throw new Error();setEvents([]);setSummary(emptySummary);setAnalytics(emptyAnalytics);setDetections([]);setFrames(0);setRoute(emptyRoute);setSelectedEvent(null);setInspecting(true);setApiStatus('online')}catch{alert('Unable to start an inspection. Make sure the detector API is running.')}}
 async function completeInspection(){if(completeBusy)return;setCompleteBusy(true);if(timerRef.current)clearInterval(timerRef.current);timerRef.current=null;try{const r=await fetch(`${API_URL}/history/complete`,{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.detail||'No inspection data to archive');setInspecting(false);setEvents([]);setSummary(emptySummary);setAnalytics(emptyAnalytics);setDetections([]);setFrames(0);setRoute(emptyRoute);setSelectedEvent(null);alert(`Inspection archived: ${d.id}`)}catch(e){alert(e instanceof Error?e.message:'Unable to archive inspection')}finally{setCompleteBusy(false)}}
 async function resetInspection(){try{await fetch(`${API_URL}/reset`,{method:'POST'})}catch{}setEvents([]);setSummary(emptySummary);setAnalytics(emptyAnalytics);setDetections([]);setFrames(0);setRoute(emptyRoute);setSelectedEvent(null)}
 function stopCamera(){if(inspecting&&(events.length>0||route.pointCount>0)){void completeInspection()}else{if(timerRef.current)clearInterval(timerRef.current);streamRef.current?.getTracks().forEach(t=>t.stop());streamRef.current=null;timerRef.current=null;setCameraOn(false);setInspecting(false)}}
 async function downloadReport(){if(reportBusy)return;setReportBusy(true);try{const response=await fetch(`${API_URL}/report.pdf`);if(!response.ok)throw new Error();const blob=await response.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='roadscan-inspection-report.pdf';document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url)}catch{alert('Unable to generate the inspection report. Make sure the detector API is running.')}finally{setReportBusy(false)}}
 async function processFrame(){if(busyRef.current)return;const video=videoRef.current,canvas=canvasRef.current;if(!video||!canvas||video.readyState<2||!inspecting||!video.videoWidth)return;busyRef.current=true;const width=Math.min(video.videoWidth,960),height=Math.round(video.videoHeight/video.videoWidth*width);canvas.width=width;canvas.height=height;canvas.getContext('2d')?.drawImage(video,0,0,width,height);try{const r=await fetch(`${API_URL}/detect`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:canvas.toDataURL('image/jpeg',.72),latitude:gpsRef.current?.[0]??null,longitude:gpsRef.current?.[1]??null,timestamp:new Date().toISOString()})});if(!r.ok)throw new Error();const data=await r.json();setDetections(data.detections||[]);setEvents(data.events||[]);setSummary(data.summary||emptySummary);setAnalytics(data.analytics||emptyAnalytics);setRoute(data.route||emptyRoute);setInferenceMs(data.inferenceMs??null);setFrames(data.frames||0);setApiStatus('online')}catch{setApiStatus('offline')}finally{busyRef.current=false}}
 function pauseInspection(){setInspecting(false);if(timerRef.current)clearInterval(timerRef.current);timerRef.current=null}
 useEffect(()=>{if(!inspecting)return;timerRef.current=setInterval(()=>void processFrame(),500);return()=>{if(timerRef.current)clearInterval(timerRef.current)}},[inspecting])
 function evidenceUrl(path:string){return path?`${API_URL}${path}`:''}; const routeDistance=route.distanceKm>=1?`${route.distanceKm.toFixed(2)} km`:`${Math.round(route.distanceMeters)} m`
 return <main className="app"><header className="topbar"><div className="brand"><div className="brand-mark">⌁</div><div><div className="brand-name">RoadScan AI</div><div className="brand-sub">Road defect detection & inspection</div></div></div><div className="status"><span className={`dot ${inspecting?'live':''}`}/>{inspecting?'LIVE INSPECTION':'STANDBY'}</div></header><section className="shell"><div className="hero"><div><h1>Live Road Inspection</h1><p className="muted">Camera → AI tracking → GPS evidence → continuous inspection route.</p></div><div className="actions"><a className="btn" href="/history">Inspection History</a><button className="btn" onClick={()=>document.getElementById('map-section')?.scrollIntoView({behavior:'smooth'})}>View Map</button><button className="btn" onClick={()=>void downloadReport()} disabled={reportBusy||events.length===0}>{reportBusy?'Generating…':'Export PDF'}</button>{inspecting?<><button className="btn" onClick={pauseInspection}>Pause Inspection</button><button className="btn primary" onClick={()=>void completeInspection()} disabled={completeBusy}>{completeBusy?'Saving…':'Finish & Save'}</button></>:<button className="btn primary" onClick={()=>void startInspection()}>Start Inspection</button>}</div></div>
 <div className="grid"><section className="card"><div className="camera-head"><div className="camera-title"><span>▣</span> Camera Feed</div><div className="live-pill">{inspecting?'● LIVE':cameraOn?'READY':'OFFLINE'}</div></div><div className="video-wrap"><video ref={videoRef} className="video" muted playsInline/><canvas ref={canvasRef} hidden/>{detections.map((d,i)=>{const v=videoRef.current;if(!v?.videoWidth)return null;const[x1,y1,x2,y2]=d.bbox;return <div key={`${d.trackId??'untracked'}-${i}`} className="bbox" style={{left:`${x1/v.videoWidth*100}%`,top:`${y1/v.videoHeight*100}%`,width:`${(x2-x1)/v.videoWidth*100}%`,height:`${(y2-y1)/v.videoHeight*100}%`}}><span>{d.label} {d.trackId!=null?`#${d.trackId} `:''}{(d.confidence*100).toFixed(0)}%</span></div>})}{!cameraOn&&<div className="video-placeholder"><div><strong>Camera feed is offline</strong><span>Start an inspection to activate the camera</span></div></div>}<div className="overlay"><div className="chip">Inference: {inspecting?'ACTIVE':'IDLE'}</div><div className="chip">API: {apiStatus.toUpperCase()}</div><div className="chip">Latency: {inferenceMs==null?'—':`${inferenceMs} ms`}</div></div></div><div style={{padding:'14px 16px',display:'flex',justifyContent:'space-between',alignItems:'center',borderTop:'1px solid #1b2638'}}><span className="muted">Route samples are recorded from real GPS received with processed camera frames.</span>{cameraOn&&<button className="btn danger" onClick={stopCamera}>Stop Camera</button>}</div></section>
 <aside className="side"><section className="card panel"><div className="panel-title">Location</div><div className="gps"><div><div style={{fontWeight:700}}>GPS {gps==='ready'?'Ready':gps==='unavailable'?'Unavailable':'Waiting'}</div><div className="gps-note">{coordinates}</div></div><div className="ready">{gps==='ready'?'●':'○'}</div></div></section><section className="card panel"><div className="panel-title">Unique Potholes</div><div className="count">{summary.total}</div><div className="count-label">Tracked inspection events</div><div className="severity"><div className="sev high"><b>{summary.high}</b><span>HIGH</span></div><div className="sev medium"><b>{summary.medium}</b><span>MEDIUM</span></div><div className="sev low"><b>{summary.low}</b><span>LOW</span></div></div><div className="muted" style={{fontSize:11,marginTop:10}}>Bands reflect AI confidence, not engineering severity.</div></section><section className="card panel"><div className="panel-title">Inspection telemetry</div><div className="metric-row"><span>Frames processed</span><b>{frames}</b></div><div className="metric-row"><span>Current detections</span><b>{detections.length}</b></div><div className="metric-row"><span>Unique potholes</span><b>{summary.total}</b></div><div className="metric-row"><span>Route points</span><b>{route.pointCount}</b></div><div className="metric-row"><span>Route distance</span><b>{routeDistance}</b></div><div className="metric-row"><span>GPS mapped potholes</span><b>{analytics.mappedPotholes}</b></div><div className="metric-row"><span>Evidence captured</span><b>{analytics.evidenceCaptured}</b></div><div className="metric-row"><span>Detector API</span><b>{apiStatus==='online'?'Online':'Offline'}</b></div></section></aside></div>
 <section className="analytics-grid"><div className="card panel"><div className="panel-title">Inspection Analytics</div><div className="analytics-score"><div><div className="score-label">Route condition score</div><div className="score-value">{analytics.conditionScore==null?'—':analytics.conditionScore}<span>/100</span></div><div className="score-band">{analytics.conditionLabel}</div></div><div className="score-ring" style={{'--score':`${analytics.conditionScore??0}%`} as React.CSSProperties}><span>{analytics.conditionScore==null?'NO DATA':`${analytics.conditionScore}`}</span></div></div><div className="analytics-metrics"><div><b>{analytics.potholesPerKm==null?'—':analytics.potholesPerKm}</b><span>Potholes / km</span></div><div><b>{analytics.confidencePercent.toFixed(1)}%</b><span>Avg. AI confidence</span></div><div><b>{analytics.mappedPotholes}</b><span>GPS hotspots</span></div><div><b>{analytics.evidenceCaptured}</b><span>Evidence frames</span></div></div></div><div className="card panel"><div className="panel-title">Confidence Distribution</div><div className="bar-row"><span>High</span><div className="bar"><i style={{width:`${summary.total?summary.high/summary.total*100:0}%`}}/></div><b>{summary.high}</b></div><div className="bar-row"><span>Medium</span><div className="bar"><i style={{width:`${summary.total?summary.medium/summary.total*100:0}%`}}/></div><b>{summary.medium}</b></div><div className="bar-row"><span>Low</span><div className="bar"><i style={{width:`${summary.total?summary.low/summary.total*100:0}%`}}/></div><b>{summary.low}</b></div><p className="muted analytics-note">Condition score is a screening metric derived from observed pothole density. It is not an engineering pavement condition index.</p></div></section>
 <div className="bottom"><section className="card" id="map-section"><div className="panel" style={{paddingBottom:10}}><div className="panel-title">Live Inspection Route & Pothole Map</div></div><InspectionMap events={events} gps={gpsPoint} routePoints={route.points}/></section><section className="card panel"><div className="panel-title">Evidence & Tracked Events</div><div className="event-list">{events.length===0?<div className="empty-events">No pothole events yet. Start inspection and detections will appear here.</div>:events.slice().reverse().slice(0,8).map(e=><button className="event-row" key={e.event_id} onClick={()=>setSelectedEvent(e)} style={{width:'100%',textAlign:'left',cursor:'pointer'}}>{e.evidence?<img className="event-thumb" src={evidenceUrl(e.evidence)} alt={`${e.event_id} evidence`}/>:<div className="event-thumb event-thumb-empty">NO IMG</div>}<div><b>{e.event_id}</b><span>Track #{e.track_id} · {e.latitude!=null?`${e.latitude.toFixed(5)}, ${e.longitude?.toFixed(5)}`:'GPS unavailable'}</span><span>Evidence {e.evidence?'captured':'unavailable'} · AI confidence band: {e.severity}</span></div><strong className={`event-${e.severity}`}>{(e.confidence*100).toFixed(0)}%</strong></button>)}</div><div className="report-actions"><a className="btn" href="/history">View Inspection History</a><button className="btn primary" onClick={()=>void downloadReport()} disabled={reportBusy||events.length===0}>{reportBusy?'Generating report…':'Export inspection PDF'}</button><button className="btn danger" onClick={()=>void resetInspection()}>Reset Inspection Data</button></div></section></div></section>
 {selectedEvent&&<div className="modal-backdrop" onClick={()=>setSelectedEvent(null)}><div className="evidence-modal" onClick={e=>e.stopPropagation()}><div className="evidence-modal-head"><div><b>{selectedEvent.event_id}</b><span>Track #{selectedEvent.track_id} · AI confidence {(selectedEvent.confidence*100).toFixed(0)}%</span></div><button className="btn" onClick={()=>setSelectedEvent(null)}>Close</button></div>{selectedEvent.evidence?<img className="evidence-image" src={evidenceUrl(selectedEvent.evidence)} alt={`${selectedEvent.event_id} captured evidence`}/>:<div className="map-empty">No evidence image was captured for this event.</div>}<div className="evidence-meta"><span>GPS: {selectedEvent.latitude!=null?`${selectedEvent.latitude.toFixed(6)}, ${selectedEvent.longitude?.toFixed(6)}`:'Unavailable'}</span><span>{new Date(selectedEvent.timestamp).toLocaleString()}</span></div></div></div>}</section></main>
}
